### ISSUE TITLE
Add support for handlesExceptions option

### ISSUE THREAD

**Issue by otisg** [sematext/winston-logsene#3]
Feedback from a Logsene user:
_The winston-logsene transport would benefit from the handlesExceptions option._

**Comment by rsteckler** [comment]
winston allows transports to [handle uncaught exceptions](https://github.com/winstonjs/winston#handling-uncaught-exceptions-with-winston).  The [Amazon-SNS](https://github.com/jesseditson/winston-sns/blob/master/lib/winston-sns.js#L48-L50) and Graylog2 transports are examples that handle this.  In node, especially, unhandled exception handling is critical because it's not compiled, strongly typed, and exception handling is "hard" to get right.  Alerts on uncaught exceptions are almost necessary even with robust unit test coverage.  
If winston-logsene handled uncaught exceptions, I wouldn't need to separate those exceptions out to their own log and tail them with logstash.

**Comment by otisg** [comment]
Big +1.  We've been wanting to capture exceptions automatically.

**Comment by megastef** [comment]
This should work now in 1.0.9: 
```
var winston = require('winston')
var Logsene = require('winston-logsene')
var logger = new winston.Logger()
logger.add(Logsene, {
  token: process.env.LOGSENE_TOKEN, 
  handleExceptions: true, 
  exitOnError: false})
```

BTW: Logstash? ;) Check out https://github.com/sematext/logagent-js

**Comment by johnpeb** [comment]
Here's a hack to emulate exitOnError:true
```
var winston = require('winston');
var winstonLogsene = require('winston-logsene');
var logseneInstance;
var logger = new winston.Logger({
  transports: [
    new winston.transports.Console({
      colorize: true,
      handleExceptions: false,
    }),
    logseneInstance = new winstonLogsene({
      token: process.env.LOGSENE,
      type: process.env.APP || 'api-unkown',
      handleExceptions: false
    })
  ]
});

process.on('uncaughtException', function (err) {
  logger.error(err.stack || err.toString());
  logseneInstance.logger.send(function() {
    process.exit(1);  
  });
});
```

**Comment by megastef** [comment]
I think this can be closed.
